services: mongodb
sudo: true
language: node_js
node_js:
- node
git:
  quiet: true
cache: npm
install:
- npm install
before_script:
- sleep 15
- mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
- cd app/back-end
- npm install
- npm run test
after_success:
- bash ./deploy_backend.sh
- cd ../front-end
- bash ./deploy_frontend.sh
env:
  global:
    - PRODUCTION=0